---
- name: Display Primary DC and CA host
  ansible.builtin.debug:
    msg: "DC: {{ ludus_adcs_dc }} | CA: {{ ludus_adcs_ca_host }}"

- name: Create an ESC13 domain user
  community.windows.win_domain_user:
    name: "{{ ludus_adcs_esc13_user }}"
    password: "{{ ludus_adcs_esc13_password }}"
    upn: "{{ ludus_adcs_esc13_user }}"
    password_never_expires: true
    user_cannot_change_password: true
    state: present
    domain_username: "{{ ludus_adcs_domain_username }}"
    domain_password: "{{ ludus_adcs_domain_password }}"
    domain_server: "{{ ludus_adcs_dc }}"

- name: Create an ESC13 domain group
  community.windows.win_domain_group:
    name: "{{ ludus_adcs_esc13_group }}"
    scope: universal
    state: present
    domain_username: "{{ ludus_adcs_domain_username }}"
    domain_password: "{{ ludus_adcs_domain_password }}"
    domain_server: "{{ ludus_adcs_dc }}"

- name: Copy ESC13 script to remote host
  ansible.windows.win_copy:
    src: files/esc13.ps1
    dest: C:\ludus\adcs\esc13.ps1

- name: Run ESC13 script
  ansible.windows.win_shell: |
    C:\ludus\adcs\esc13.ps1 -esc13group '{{ ludus_adcs_esc13_group }}' -esc13templateName '{{ ludus_adcs_esc13_template }}' -esc13user '{{ ludus_adcs_esc13_user }}'
  become: true
  become_method: runas
  vars:
    ansible_become: true
    ansible_become_method: runas
    domain_name: "{{ ludus_adcs_domain }}"
    ansible_become_user: "{{ ludus_adcs_domain_username }}"
    ansible_become_password: "{{ ludus_adcs_domain_password }}"
  register: esc13_output

- name: Output ESC13 script result
  ansible.builtin.debug:
    var: esc13_output

- name: Give the ESC13 group something juicy for the operator to abuse it
  win_shell: |
    whoami
  args:
    executable: powershell.exe
